const Product = require('../models/Product');

const products = [
  { name: 'Home Kit 2025/26', slug: 'home-kit-2025-26', category: 'kit', price: 6500, salePrice: 5500, onSale: true, isNew: true, images: ['/images/kit-home.jpg'], sizes: [{ size: 'XS', stock: 20 }, { size: 'S', stock: 50 }, { size: 'M', stock: 80 }, { size: 'L', stock: 100 }, { size: 'XL', stock: 60 }, { size: '2XL', stock: 30 }, { size: '3XL', stock: 15 }], totalStock: 355, featured: true, description: 'The iconic Celtics Green home kit. Worn on matchdays at the fortress.' },
  { name: 'Away Kit 2025/26', slug: 'away-kit-2025-26', category: 'kit', price: 6500, salePrice: null, onSale: false, isNew: true, images: ['/images/kit-away.jpg'], sizes: [{ size: 'XS', stock: 15 }, { size: 'S', stock: 40 }, { size: 'M', stock: 70 }, { size: 'L', stock: 80 }, { size: 'XL', stock: 50 }, { size: '2XL', stock: 25 }], totalStock: 280, featured: true, description: 'Striking white away kit with green accents. For conquering on the road.' },
  { name: 'Third Kit 2025/26', slug: 'third-kit-2025-26', category: 'kit', price: 7000, salePrice: null, onSale: false, isNew: true, images: ['/images/kit-third.jpg'], sizes: [{ size: 'S', stock: 30 }, { size: 'M', stock: 55 }, { size: 'L', stock: 65 }, { size: 'XL', stock: 40 }], totalStock: 190, featured: false, description: 'Limited edition black third kit with gold accents.' },
  { name: 'Goalkeeper Kit 2025/26', slug: 'goalkeeper-kit-2025-26', category: 'kit', price: 6500, salePrice: null, onSale: false, isNew: false, images: ['/images/kit-gk.jpg'], sizes: [{ size: 'S', stock: 20 }, { size: 'M', stock: 35 }, { size: 'L', stock: 40 }, { size: 'XL', stock: 25 }], totalStock: 120, featured: false, description: 'High-visibility goalkeeper jersey in neon yellow.' },
  { name: 'Women\'s Kit 2025/26', slug: 'womens-kit-2025-26', category: 'kit', price: 6500, salePrice: 5800, onSale: true, isNew: false, images: ['/images/kit-women.jpg'], sizes: [{ size: 'XS', stock: 25 }, { size: 'S', stock: 45 }, { size: 'M', stock: 50 }, { size: 'L', stock: 35 }, { size: 'XL', stock: 15 }], totalStock: 170, featured: false, description: 'Tailored fit for the Celtics faithful.' },
  { name: 'Youth Kit 2025/26', slug: 'youth-kit-2025-26', category: 'kit', price: 4500, salePrice: 3800, onSale: true, isNew: false, images: ['/images/kit-youth.jpg'], sizes: [{ size: '3-4Y', stock: 30 }, { size: '5-6Y', stock: 40 }, { size: '7-8Y', stock: 45 }, { size: '9-10Y', stock: 35 }, { size: '11-12Y', stock: 25 }, { size: '13-14Y', stock: 20 }], totalStock: 195, featured: false, description: 'Mini Celtics fan gear. Same quality, smaller size.' },
  { name: 'Training Kit 2025/26', slug: 'training-kit-2025-26', category: 'training', price: 4500, salePrice: 3500, onSale: true, isNew: false, images: ['/images/training-kit.jpg'], sizes: [{ size: 'S', stock: 40 }, { size: 'M', stock: 60 }, { size: 'L', stock: 70 }, { size: 'XL', stock: 45 }, { size: '2XL', stock: 20 }], totalStock: 235, featured: false, description: 'Training wear worn by the first team.' },
  { name: 'Training Shorts', slug: 'training-shorts', category: 'training', price: 2500, salePrice: 2000, onSale: true, isNew: false, images: ['/images/training-kit.jpg'], sizes: [{ size: 'S', stock: 50 }, { size: 'M', stock: 80 }, { size: 'L', stock: 80 }, { size: 'XL', stock: 40 }], totalStock: 250, featured: false, description: 'Lightweight training shorts with club crest.' },
  { name: 'Training Jacket', slug: 'training-jacket', category: 'training', price: 5500, salePrice: null, onSale: false, isNew: false, images: ['/images/jacket.jpg'], sizes: [{ size: 'S', stock: 25 }, { size: 'M', stock: 40 }, { size: 'L', stock: 45 }, { size: 'XL', stock: 30 }], totalStock: 140, featured: false, description: 'Water-resistant zip-up training jacket.' },
  { name: 'Official Scarf', slug: 'official-scarf', category: 'accessory', price: 2000, salePrice: 1500, onSale: true, isNew: false, images: ['/images/scarf.jpg'], sizes: [{ size: 'One Size', stock: 200 }], totalStock: 200, featured: true, description: 'Green and black woven scarf with club crest.' },
  { name: 'Snapback Cap', slug: 'snapback-cap', category: 'accessory', price: 1800, salePrice: null, onSale: false, isNew: false, images: ['/images/cap.jpg'], sizes: [{ size: 'One Size', stock: 150 }], totalStock: 150, featured: false, description: 'Adjustable snapback cap with embroidered NCFC logo.' },
  { name: 'Club Hoodie', slug: 'club-hoodie', category: 'accessory', price: 5000, salePrice: 4200, onSale: true, isNew: false, images: ['/images/jacket.jpg'], sizes: [{ size: 'S', stock: 35 }, { size: 'M', stock: 55 }, { size: 'L', stock: 60 }, { size: 'XL', stock: 35 }], totalStock: 185, featured: true, description: 'Premium heavyweight hoodie with Celtics crest.' },
  { name: 'Kitbag', slug: 'kitbag', category: 'accessory', price: 3500, salePrice: null, onSale: false, isNew: false, images: ['/images/bag.jpg'], sizes: [{ size: 'One Size', stock: 80 }], totalStock: 80, featured: false, description: 'Duffel bag with shoe compartment. Pro-grade.' },
  { name: 'Beanie Hat', slug: 'beanie-hat', category: 'accessory', price: 1500, salePrice: 1200, onSale: true, isNew: false, images: ['/images/cap.jpg'], sizes: [{ size: 'One Size', stock: 100 }], totalStock: 100, featured: false, description: 'Knit beanie with embroidered crest.' },
  { name: 'Phone Case', slug: 'phone-case', category: 'accessory', price: 1200, salePrice: null, onSale: false, isNew: false, images: ['/images/cap.jpg'], sizes: [{ size: 'Universal', stock: 200 }], totalStock: 200, featured: false, description: 'Impact-resistant phone case with Celtics graphics.' },
  { name: 'Autographed Ball', slug: 'autographed-ball', category: 'premium', price: 15000, salePrice: 12000, onSale: true, isNew: false, images: ['/images/kit-home.jpg'], sizes: [{ size: 'Standard', stock: 20 }], totalStock: 20, featured: true, description: 'Match ball autographed by the first-team squad.' },
  { name: 'Framed Jersey', slug: 'framed-jersey', category: 'premium', price: 25000, salePrice: null, onSale: false, isNew: true, images: ['/images/kit-home.jpg'], sizes: [{ size: 'One Size', stock: 10 }], totalStock: 10, featured: true, description: 'Signed, framed home jersey in a display case.' },
  { name: 'VIP Matchday Experience', slug: 'vip-matchday-experience', category: 'premium', price: 35000, salePrice: null, onSale: false, isNew: false, images: ['/images/ticket-bg.jpg'], sizes: [{ size: 'Single', stock: 50 }], totalStock: 50, featured: false, description: 'Premium hospitality including box seats, dining, and meet-and-greet.' },
  { name: 'Annual Membership', slug: 'annual-membership', category: 'premium', price: 8000, salePrice: 6500, onSale: true, isNew: false, images: ['/images/crest.png'], sizes: [{ size: 'Individual', stock: 1000 }, { size: 'Family', stock: 500 }], totalStock: 1500, featured: false, description: 'Exclusive member benefits, discounts, and priority ticket access.' },
  { name: 'Stadium Tour Voucher', slug: 'stadium-tour-voucher', category: 'premium', price: 3000, salePrice: null, onSale: false, isNew: false, images: ['/images/stadium.jpg'], sizes: [{ size: 'Adult', stock: 200 }, { size: 'Child', stock: 150 }], totalStock: 350, featured: false, description: 'Behind-the-scenes stadium tour voucher.' },
];

const seedProducts = async () => {
  await Product.deleteMany({});
  await Product.insertMany(products);
  console.log('Products seeded: 20 products');
};

module.exports = seedProducts;
