const mongoose = require('mongoose');
const Player = require('../models/Player');

const players = [
  { firstName: 'James', lastName: 'Omondi', jerseyNumber: 1, position: 'GK', team: 'men', nationality: 'Kenya', dateOfBirth: new Date('1995-03-15'), height: 188, weight: 82, image: '/images/player-1.jpg', stats: { appearances: 28, goals: 0, assists: 0, cleanSheets: 12, rating: 7.4, yellowCards: 2, redCards: 0 }, career: [{ club: 'Gor Mahia', years: '2016-2020', appearances: 98, goals: 0 }, { club: 'Nairobi Celtics', years: '2020-', appearances: 28, goals: 0 }] },
  { firstName: 'David', lastName: 'Mwangi', jerseyNumber: 2, position: 'DEF', team: 'men', nationality: 'Kenya', dateOfBirth: new Date('1998-07-22'), height: 180, weight: 75, image: '/images/player-2.jpg', stats: { appearances: 31, goals: 3, assists: 5, cleanSheets: 10, rating: 7.1, yellowCards: 4, redCards: 0 }, career: [{ club: 'AFC Leopards', years: '2017-2021', appearances: 87, goals: 5 }, { club: 'Nairobi Celtics', years: '2021-', appearances: 31, goals: 3 }] },
  { firstName: 'Samuel', lastName: 'Kiprop', jerseyNumber: 3, position: 'DEF', team: 'men', nationality: 'Kenya', dateOfBirth: new Date('1997-11-10'), height: 184, weight: 78, image: '/images/player-3.jpg', stats: { appearances: 26, goals: 1, assists: 3, cleanSheets: 9, rating: 6.9, yellowCards: 5, redCards: 1 }, career: [{ club: 'Tusker FC', years: '2018-2022', appearances: 72, goals: 3 }, { club: 'Nairobi Celtics', years: '2022-', appearances: 26, goals: 1 }] },
  { firstName: 'Brian', lastName: 'Odhiambo', jerseyNumber: 4, position: 'DEF', team: 'men', nationality: 'Kenya', dateOfBirth: new Date('1996-04-05'), height: 186, weight: 80, image: '/images/player-4.jpg', stats: { appearances: 33, goals: 4, assists: 2, cleanSheets: 14, rating: 7.6, yellowCards: 3, redCards: 0 }, career: [{ club: 'Bandari FC', years: '2015-2019', appearances: 110, goals: 8 }, { club: 'KCB FC', years: '2019-2021', appearances: 54, goals: 3 }, { club: 'Nairobi Celtics', years: '2021-', appearances: 33, goals: 4 }] },
  { firstName: 'Eric', lastName: 'Wanjala', jerseyNumber: 5, position: 'DEF', team: 'men', nationality: 'Kenya', dateOfBirth: new Date('1999-09-18'), height: 179, weight: 73, image: '/images/player-5.jpg', stats: { appearances: 22, goals: 0, assists: 1, cleanSheets: 7, rating: 6.7, yellowCards: 6, redCards: 0 }, career: [{ club: 'Mathare United', years: '2018-2022', appearances: 65, goals: 1 }, { club: 'Nairobi Celtics', years: '2022-', appearances: 22, goals: 0 }] },
  { firstName: 'Kevin', lastName: 'Ochieng', jerseyNumber: 6, position: 'MID', team: 'men', nationality: 'Kenya', dateOfBirth: new Date('1997-01-30'), height: 175, weight: 70, image: '/images/player-6.jpg', stats: { appearances: 34, goals: 7, assists: 11, rating: 8.1, yellowCards: 3, redCards: 0 }, career: [{ club: 'Gor Mahia', years: '2016-2020', appearances: 92, goals: 15 }, { club: 'Nairobi Celtics', years: '2020-', appearances: 34, goals: 7 }] },
  { firstName: 'Michael', lastName: 'Kamau', jerseyNumber: 7, position: 'MID', team: 'men', nationality: 'Kenya', dateOfBirth: new Date('2000-06-14'), height: 172, weight: 68, image: '/images/player-7.jpg', stats: { appearances: 29, goals: 5, assists: 8, rating: 7.8, yellowCards: 2, redCards: 0 }, career: [{ club: 'Nairobi Celtics Academy', years: '2018-2020', appearances: 45, goals: 12 }, { club: 'Nairobi Celtics', years: '2020-', appearances: 29, goals: 5 }] },
  { firstName: 'Patrick', lastName: 'Njoroge', jerseyNumber: 8, position: 'MID', team: 'men', nationality: 'Kenya', dateOfBirth: new Date('1995-08-20'), height: 178, weight: 74, image: '/images/player-8.jpg', stats: { appearances: 32, goals: 9, assists: 6, rating: 7.9, yellowCards: 5, redCards: 1 }, career: [{ club: 'Sofapaka', years: '2014-2018', appearances: 105, goals: 22 }, { club: 'Ulinzi Stars', years: '2018-2021', appearances: 78, goals: 16 }, { club: 'Nairobi Celtics', years: '2021-', appearances: 32, goals: 9 }] },
  { firstName: 'Daniel', lastName: 'Mutua', jerseyNumber: 9, position: 'FWD', team: 'men', nationality: 'Kenya', dateOfBirth: new Date('1994-12-03'), height: 185, weight: 81, image: '/images/player-9.jpg', stats: { appearances: 30, goals: 18, assists: 4, rating: 8.4, yellowCards: 1, redCards: 0 }, career: [{ club: 'Tusker FC', years: '2015-2019', appearances: 88, goals: 42 }, { club: 'KCB FC', years: '2019-2021', appearances: 56, goals: 28 }, { club: 'Nairobi Celtics', years: '2021-', appearances: 30, goals: 18 }] },
  { firstName: 'Joseph', lastName: 'Barasa', jerseyNumber: 10, position: 'FWD', team: 'men', nationality: 'Kenya', dateOfBirth: new Date('1998-02-28'), height: 177, weight: 72, image: '/images/player-10.jpg', stats: { appearances: 27, goals: 14, assists: 7, rating: 8.2, yellowCards: 2, redCards: 0 }, career: [{ club: 'Bandari FC', years: '2017-2021', appearances: 82, goals: 31 }, { club: 'Nairobi Celtics', years: '2021-', appearances: 27, goals: 14 }] },
  { firstName: 'Peter', lastName: 'Onyango', jerseyNumber: 11, position: 'FWD', team: 'men', nationality: 'Kenya', dateOfBirth: new Date('2001-05-11'), height: 183, weight: 76, image: '/images/player-11.jpg', stats: { appearances: 19, goals: 8, assists: 3, rating: 7.3, yellowCards: 0, redCards: 0 }, career: [{ club: 'Nairobi Celtics Academy', years: '2019-2022', appearances: 52, goals: 20 }, { club: 'Nairobi Celtics', years: '2022-', appearances: 19, goals: 8 }] },
  { firstName: 'John', lastName: 'Kiprono', jerseyNumber: 12, position: 'GK', team: 'men', nationality: 'Kenya', dateOfBirth: new Date('2002-08-08'), height: 191, weight: 85, image: '/images/player-12.jpg', stats: { appearances: 6, goals: 0, assists: 0, cleanSheets: 3, rating: 6.8, yellowCards: 1, redCards: 0 }, career: [{ club: 'Nairobi Celtics Academy', years: '2020-2023', appearances: 30, goals: 0 }, { club: 'Nairobi Celtics', years: '2023-', appearances: 6, goals: 0 }] },
  { firstName: 'Francis', lastName: 'Macharia', jerseyNumber: 13, position: 'DEF', team: 'men', nationality: 'Kenya', dateOfBirth: new Date('2000-10-15'), height: 182, weight: 77, image: '/images/player-13.jpg', stats: { appearances: 18, goals: 0, assists: 2, cleanSheets: 6, rating: 6.6, yellowCards: 4, redCards: 0 }, career: [{ club: 'Posta Rangers', years: '2019-2022', appearances: 58, goals: 1 }, { club: 'Nairobi Celtics', years: '2022-', appearances: 18, goals: 0 }] },
  { firstName: 'Timothy', lastName: 'Ndungu', jerseyNumber: 14, position: 'MID', team: 'men', nationality: 'Kenya', dateOfBirth: new Date('1999-03-27'), height: 176, weight: 69, image: '/images/player-14.jpg', stats: { appearances: 25, goals: 3, assists: 5, rating: 7.0, yellowCards: 3, redCards: 0 }, career: [{ club: 'Wazito FC', years: '2018-2021', appearances: 71, goals: 9 }, { club: 'Nairobi Celtics', years: '2021-', appearances: 25, goals: 3 }] },
  { firstName: 'Alex', lastName: 'Wambua', jerseyNumber: 15, position: 'DEF', team: 'men', nationality: 'Kenya', dateOfBirth: new Date('2001-07-19'), height: 181, weight: 75, image: '/images/player-15.jpg', stats: { appearances: 15, goals: 1, assists: 0, cleanSheets: 4, rating: 6.5, yellowCards: 3, redCards: 0 }, career: [{ club: 'Muranga SEAL', years: '2020-2023', appearances: 45, goals: 2 }, { club: 'Nairobi Celtics', years: '2023-', appearances: 15, goals: 1 }] },
  { firstName: 'Mark', lastName: 'Kosgei', jerseyNumber: 16, position: 'MID', team: 'men', nationality: 'Kenya', dateOfBirth: new Date('1996-09-14'), height: 174, weight: 71, image: '/images/player-16.jpg', stats: { appearances: 30, goals: 4, assists: 9, rating: 7.5, yellowCards: 6, redCards: 0 }, career: [{ club: 'Sofapaka', years: '2016-2020', appearances: 95, goals: 14 }, { club: 'Nairobi Celtics', years: '2020-', appearances: 30, goals: 4 }] },
  { firstName: 'Collins', lastName: 'Otieno', jerseyNumber: 17, position: 'FWD', team: 'men', nationality: 'Kenya', dateOfBirth: new Date('1997-11-25'), height: 179, weight: 73, image: '/images/player-17.jpg', stats: { appearances: 24, goals: 10, assists: 3, rating: 7.7, yellowCards: 2, redCards: 0 }, career: [{ club: 'Talanta FC', years: '2017-2020', appearances: 69, goals: 23 }, { club: 'AFC Leopards', years: '2020-2022', appearances: 51, goals: 17 }, { club: 'Nairobi Celtics', years: '2022-', appearances: 24, goals: 10 }] },
  { firstName: 'Emmanuel', lastName: 'Kipchumba', jerseyNumber: 18, position: 'MID', team: 'men', nationality: 'Kenya', dateOfBirth: new Date('2002-12-01'), height: 170, weight: 66, image: '/images/player-18.jpg', stats: { appearances: 12, goals: 2, assists: 4, rating: 7.2, yellowCards: 1, redCards: 0 }, career: [{ club: 'Nairobi Celtics Academy', years: '2020-2023', appearances: 40, goals: 8 }, { club: 'Nairobi Celtics', years: '2023-', appearances: 12, goals: 2 }] },
  { firstName: 'William', lastName: 'Ruto', jerseyNumber: 19, position: 'DEF', team: 'men', nationality: 'Kenya', dateOfBirth: new Date('1998-05-09'), height: 187, weight: 82, image: '/images/player-19.jpg', stats: { appearances: 21, goals: 2, assists: 1, cleanSheets: 8, rating: 6.8, yellowCards: 5, redCards: 1 }, career: [{ club: 'KCB FC', years: '2018-2022', appearances: 66, goals: 4 }, { club: 'Nairobi Celtics', years: '2022-', appearances: 21, goals: 2 }] },
  { firstName: 'Stephen', lastName: 'Kariuki', jerseyNumber: 20, position: 'MID', team: 'men', nationality: 'Kenya', dateOfBirth: new Date('2000-01-17'), height: 173, weight: 68, image: '/images/player-20.jpg', stats: { appearances: 14, goals: 1, assists: 2, rating: 6.4, yellowCards: 2, redCards: 0 }, career: [{ club: 'Mathare United', years: '2019-2022', appearances: 48, goals: 4 }, { club: 'Nairobi Celtics', years: '2022-', appearances: 14, goals: 1 }] },
  { firstName: 'Benard', lastName: 'Mutiso', jerseyNumber: 21, position: 'FWD', team: 'men', nationality: 'Kenya', dateOfBirth: new Date('2003-06-30'), height: 184, weight: 78, image: '/images/player-21.jpg', stats: { appearances: 8, goals: 3, assists: 1, rating: 6.9, yellowCards: 0, redCards: 0 }, career: [{ club: 'Nairobi Celtics Academy', years: '2021-2023', appearances: 35, goals: 15 }, { club: 'Nairobi Celtics', years: '2023-', appearances: 8, goals: 3 }] },
  { firstName: 'Vincent', lastName: 'Ouma', jerseyNumber: 22, position: 'GK', team: 'men', nationality: 'Kenya', dateOfBirth: new Date('1994-02-14'), height: 186, weight: 80, image: '/images/player-22.jpg', stats: { appearances: 2, goals: 0, assists: 0, cleanSheets: 1, rating: 6.3, yellowCards: 0, redCards: 0 }, career: [{ club: 'Posta Rangers', years: '2015-2019', appearances: 55, goals: 0 }, { club: 'Nairobi Celtics', years: '2019-2023', appearances: 12, goals: 0 }, { club: 'Nairobi Celtics', years: '2023-', appearances: 2, goals: 0 }] },
];

const seedPlayers = async () => {
  await Player.deleteMany({});
  await Player.insertMany(players);
  console.log('Players seeded: 22 players');
};

module.exports = seedPlayers;
