const News = require('../models/News');

const articles = [
  { title: 'Celtics Crush Gor Mahia 3-0 in KSL Derby', slug: 'celtics-crush-gor-mahia-3-0', excerpt: 'A dominant display at the fortress sees Celtics go top of the table with a comprehensive victory over rivals Gor Mahia.', content: 'Nairobi Celtics FC delivered a masterclass performance at the Nairobi Celtics Stadium, dismantling arch-rivals Gor Mahia 3-0 in front of a record crowd of 45,000 fans. Daniel Mutua opened the scoring in the 23rd minute with a clinical finish from inside the box. Kevin Ochieng doubled the lead just before halftime with a spectacular volley from 25 yards. Joseph Barasa sealed the victory in the 67th minute, rounding off a swift counter-attack. The win propels Celtics to the top of the KSL standings with 48 points from 18 matches.', category: 'Match Reports', author: 'Nairobi Celtics FC', thumbnail: '/images/news-1.jpg', featured: true, publishedAt: new Date('2025-10-15'), tags: ['Match Report', 'KSL', 'Derby'] },
  { title: 'Celtics Confirm Signing of Kenyan International', slug: 'celtics-sign-kenyan-international', excerpt: 'Nairobi Celtics FC is delighted to announce the signing of highly-rated Kenyan international midfielder in a record transfer deal.', content: 'Nairobi Celtics FC has completed the signing of Kenyan international midfielder Collins Otieno from AFC Leopards on a four-year deal. The 27-year-old, who has 14 caps for the Kenya national team, joins for a club-record fee. "This is a dream move," said Otieno. "Nairobi Celtics is the biggest club in Kenya right now, and I want to help bring trophies to this passionate fanbase." Head Coach praised the signing, calling Otieno "a game-changer who will add immense quality to our midfield."', category: 'Transfer News', author: 'Transfer Desk', thumbnail: '/images/news-2.jpg', featured: true, publishedAt: new Date('2025-09-28'), tags: ['Transfers', 'Signing', 'Kenyan International'] },
  { title: 'Academy Graduate Signs First Professional Contract', slug: 'academy-graduate-first-pro-contract', excerpt: '18-year-old sensation Emmanuel Kipchumba has signed his first professional contract with Nairobi Celtics FC, committing his future to the club until 2028.', content: 'Nairobi Celtics Academy product Emmanuel Kipchumba has signed his first professional contract, committing to the club until 2028. The attacking midfielder, who has been with the Celtics Academy since the age of 10, made his first-team debut last season. "This is everything I have worked for since I was a kid," said Kipchumba. "Wearing the Celtics green is an honor, and I will give everything for this club." Kipchumba is regarded as one of the brightest prospects in Kenyan football, drawing comparisons to some of the greats.', category: 'Academy', author: 'Academy Staff', thumbnail: '/images/news-3.jpg', featured: false, publishedAt: new Date('2025-09-20'), tags: ['Academy', 'Youth', 'Contract'] },
  { title: 'Community Shield: Celtics to Face Tusker FC', slug: 'community-shield-celtics-tusker', excerpt: 'Nairobi Celtics will face Tusker FC in the annual Community Shield match at the Nairobi Celtics Stadium.', content: 'The Kenyan Football Federation has confirmed that Nairobi Celtics FC will face Tusker FC in this year\'s Community Shield, marking the traditional curtain-raiser to the new KSL season. The match is scheduled for Saturday, 10 January 2026 at the Nairobi Celtics Stadium. "The Community Shield is always a special occasion," said the Celtics captain. "Facing a strong side like Tusker will be the perfect preparation for the season ahead." Tickets go on sale next week, with the club expecting a sell-out crowd.', category: 'Club News', author: 'Club Communications', thumbnail: '/images/news-4.jpg', featured: false, publishedAt: new Date('2025-12-01'), tags: ['Community Shield', 'Fixture', 'Tusker'] },
  { title: 'Celtics Women\'s Team Launch Inaugural Season', slug: 'celtics-women-launch-inaugural-season', excerpt: 'Nairobi Celtics FC Women\'s team officially launches its inaugural season in the Kenya Women\'s Premier League.', content: 'Nairobi Celtics FC is proud to announce the launch of its women\'s team, who will compete in the Kenya Women\'s Premier League starting next season. The team will be based at the Celtics Training Campus and will play home matches at the Mini Stadium. "Football is for everyone, and we are committed to growing the women\'s game in Kenya," said the club chairman. "We have assembled a talented squad and coaching staff, and we believe Celtics Women can compete at the highest level." The club will hold open trials next month.', category: 'Club News', author: 'Women\'s Football Desk', thumbnail: '/images/news-5.jpg', featured: false, publishedAt: new Date('2025-11-15'), tags: ['Women\'s Team', 'Launch', 'New Season'] },
  { title: 'Stadium Expansion Plans Unveiled', slug: 'stadium-expansion-plans-unveiled', excerpt: 'Nairobi Celtics FC unveils ambitious plans to expand the Main Stadium to 100,000 capacity.', content: 'Nairobi Celtics FC has unveiled ambitious plans to expand the Main Stadium from its current 88,500 capacity to 100,000, making it the largest stadium in East Africa. The expansion project, estimated to cost KES 5 billion, includes a new upper tier on the east stand, additional corporate boxes, and state-of-the-art facilities. Construction is expected to begin in June 2026 and be completed by August 2027. The club will play some home matches at alternative venues during the construction period. "This expansion reflects our ambition to become a top-tier club in Africa," said the club CEO.', category: 'Club News', author: 'Communications Team', thumbnail: '/images/news-6.jpg', featured: true, publishedAt: new Date('2025-10-30'), tags: ['Stadium', 'Expansion', 'Infrastructure'] },
  { title: 'Celtics Advance to CAF CL Group Stage', slug: 'celtics-advance-caf-cl-group-stage', excerpt: 'Nairobi Celtics FC secures a historic spot in the CAF Champions League group stage for the first time.', content: 'Nairobi Celtics FC has made history by qualifying for the CAF Champions League group stage for the first time in the club\'s history. A 2-1 aggregate victory over AS Vita Club of DR Congo secured their place among Africa\'s elite. "This is a monumental achievement for the club," said the head coach. "We have worked tirelessly to reach this level, and we will compete with everything we have." The group stage draw is scheduled for next month, with Celtics potentially facing some of Africa\'s biggest clubs like Al Ahly, Wydad Casablanca, and Esperance.', category: 'Match Reports', author: 'Continental Desk', thumbnail: '/images/news-1.jpg', featured: true, publishedAt: new Date('2025-09-05'), tags: ['CAF CL', 'History', 'Qualification'] },
  { title: 'Celtics Academy Scouting Network Expands to 15 Counties', slug: 'academy-scouting-network-15-counties', excerpt: 'Nairobi Celtics FC expands its academy scouting network to 15 counties across Kenya, discovering raw talent from all corners of the nation.', content: 'Nairobi Celtics FC\'s academy scouting network has expanded to cover 15 counties across Kenya, from Kakamega to Mombasa, as part of the club\'s commitment to developing homegrown talent. The expanded network includes full-time scouts in Nairobi, Kiambu, Kisumu, Nakuru, Uasin Gishu, Meru, Machakos, Kilifi, Mombasa, Kakamega, Siaya, Homa Bay, Trans Nzoia, Laikipia, and Nandi counties. "Kenya is blessed with immense football talent," said the Academy Director. "Our goal is to leave no stone unturned in identifying and nurturing the next generation of Celtics stars."', category: 'Academy', author: 'Academy Staff', thumbnail: '/images/news-2.jpg', featured: false, publishedAt: new Date('2025-11-20'), tags: ['Academy', 'Scouting', 'Youth Development'] },
  { title: 'Community Program Reaches 10,000 Children', slug: 'community-program-10000-children', excerpt: 'Nairobi Celtics FC\'s community outreach program has reached over 10,000 children across Nairobi\'s underserved communities.', content: 'Nairobi Celtics FC\'s award-winning community program "Celtics for All" has reached a milestone of 10,000 children across Nairobi\'s underserved communities. The program, which provides free football coaching, mentorship, and educational support, operates in 20 centers across the city. "Football has the power to transform lives," said the Community Program Director. "Through Celtics for All, we are not just teaching football skills — we are building character, promoting education, and creating opportunities." The club plans to expand the program to five additional counties next year.', category: 'Community', author: 'Community Team', thumbnail: '/images/news-3.jpg', featured: false, publishedAt: new Date('2025-10-10'), tags: ['Community', 'Outreach', 'Social Impact'] },
  { title: 'KSL Mid-Season Review: Celtics Top of the Table', slug: 'ksl-mid-season-review-celtics-top', excerpt: 'As the KSL season reaches its midway point, Nairobi Celtics sit top of the table with an impressive unbeaten run.', content: 'The KSL season has reached its midway point, and Nairobi Celtics FC sits proudly at the top of the table with 42 points from 17 matches — eight points clear of second-placed Gor Mahia. The Green Machine has been in scintillating form, scoring 38 goals while conceding just 12. Key players Daniel Mutua (12 goals) and Kevin Ochieng (7 assists) have been instrumental. "We are pleased with our position but know there is still a long way to go," said the head coach. "The second half of the season will be even more challenging as teams fight for position."', category: 'Club News', author: 'Analytics Team', thumbnail: '/images/news-4.jpg', featured: false, publishedAt: new Date('2025-11-01'), tags: ['KSL', 'Mid-Season', 'Review'] },
  { title: 'Transfer Window: Celtics Complete Double Signing', slug: 'transfer-window-double-signing', excerpt: 'Nairobi Celtics FC has completed two more signings ahead of the January transfer window closing.', content: 'Nairobi Celtics FC has completed a double signing ahead of the January transfer deadline, bringing in two promising players to bolster the squad for the second half of the season. Defender Mark Kosgei joins from Sofapaka, while forward Benard Mutiso arrives from the Celtics Academy. "We have strengthened in key areas," said the Sporting Director. "Mark brings experience and leadership to our backline, while Benard is one of the most exciting young talents in the country." Both players are expected to be available for the weekend\'s match against Bandari FC.', category: 'Transfer News', author: 'Transfer Desk', thumbnail: '/images/news-5.jpg', featured: false, publishedAt: new Date('2026-01-15'), tags: ['Transfers', 'January Window', 'Squad'] },
  { title: 'Celtics Launch Official Mobile App', slug: 'celtics-launch-mobile-app', excerpt: 'Nairobi Celtics FC launches its official mobile app with ticketing, shop, and exclusive content.', content: 'Nairobi Celtics FC has launched its official mobile application, available for both iOS and Android. The app provides fans with a comprehensive digital experience, including mobile ticketing, shop access, live match updates, exclusive video content, and push notifications for news and events. "This app brings Celtics City directly to fans\' pockets," said the Digital Director. "From buying tickets to ordering kits to watching behind-the-scenes content, the app is the ultimate companion for every Celtics fan." The app is free to download from the App Store and Google Play Store.', category: 'Club News', author: 'Digital Team', thumbnail: '/images/news-6.jpg', featured: false, publishedAt: new Date('2025-12-15'), tags: ['App', 'Digital', 'Technology'] },
];

const seedNews = async () => {
  await News.deleteMany({});
  await News.insertMany(articles);
  console.log('News seeded: 12 articles');
};

module.exports = seedNews;
